# Model Assumptions
NUM_OF_ADULTS = 227e6
MINIMUM_WAGE = 7.25
HOURS_PER_WEEK = 40
WEEKS_PER_YEAR = 50
BASIC_INCOME = MINIMUM_WAGE * HOURS_PER_WEEK * WEEKS_PER_YEAR
LABOUR_FORCE = 154e6
DISABLED_ADULTS = 21e6
US_GOV_WEALTH_TRANSFERS = 3369e9
